apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplain
  namespace: argocd
spec:
  project: default
  source:
    chart: crossplane-stable/crossplane
    repoURL: https://charts.crossplane.io/stable
    helm:
      releaseName: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system