apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplain
  namespace: argocd
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.6.3
    helm:
      releaseName: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true