apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: vela-core
    repoURL: https://charts.kubevela.net/core
    targetRevision: 1.2.4
    helm:
      releaseName: kubevela
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true